# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dlai',
                'doc_host': 'https://jatintyagi7.github.io',
                'git_url': 'https://github.com/jatintyagi7/dlai',
                'lib_path': 'dlai'},
  'syms': { 'dlai.core': {'dlai.core.foo': ('core.html#foo', 'dlai/core.py')},
            'dlai.datasets': {'dlai.datasets.implement_dataset': ('datasets.html#implement_dataset', 'dlai/datasets.py')}}}