ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "dlai"
  site-url: "https://jatintyagi7.github.io/dlai"
  description: "reimplementation based on the fastai new course(course22_p2)"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/jatintyagi7/dlai"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/jatintyagi7/dlai"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
